### PR TITLE
UI hotfix

### LINKED ISSUE #42: John Molson Address is wrong
**Problem:**
When selecting john molson as a destination or starting point, the address routes to a random place

**How to Replicate:**
1. Open the app
2. Open directions
3. Select starting location as John molson
4. Observe error

**Additional context**
Image

### LINKED ISSUE #48: Left Slide Menu Opens Twice
**Problem:**
When clicking on the 3 bars to open the menu, if clicked twice, it opens 2 menus.

**How to Replicate:**
1. Go to Map Activity
2. Click on 3 bars twice very quickly
3. See 2 menus pop up.

**Additional context**

https://github.com/user-attachments/assets/601346d3-9bc6-48ee-b551-1c437892c49a

### LINKED ISSUE #50: Change Building Selection Flow (UT)
### Description
From the feedback from usability testing, getting the detailed descriptions of the buildings is not obvious. The issue highlights the feedback from Task 1. Find information about the hall building

### Details
The following changes should be done based on the feedback received.

- [x] Get a new Icon that is more descriptive such as a ? bubble with a better building icon.

- [ ] Move the button so it is still displayed when the navigation menu is open

- [ ] (Optional) include (?) info buttons in search building menu

### Additional information

Image

Image

### LINKED ISSUE #51: Navigation Flow Changes (UT)
### Description
From the feedback from usability testing, user found some issues in regard to the navigation flow. This is from task 3. Find 3 ways to open the navigation menu.

### Details
The following changes should be done based on the feedback received.

- [ ] When pressing on a new location in the search bar, the camera should move to that location instead of my current location.

- [x] The location button should work and center the camera to my position

- [x] Make the search icon clickable similar to the bar or remove the icon entirely

### Additional information

Image

Image

### PR DESCRIPTION
**Pull request by Kayram2710**
This is quick PR to address certain UI hotfixes:
- The main menu button fast click bug
- The campus map change for usability testing
- Getting rid of the search icon

### CODE REVIEW

File: app/src/main/java/minicap/concordia/campusnav/screens/MapsActivity.java [hunk 1]
```diff
@@ -187,6 +196,21 @@ protected void onCreate(Bundle savedInstanceState) {
         bottomSheetBehavior.setHalfExpandedRatio(0.01f);
         bottomSheetBehavior.setState(BottomSheetBehavior.STATE_COLLAPSED);
 
+        //Adding bottom sheet call back to allow building view button to slide with bottom sheet
+        bottomSheetBehavior.addBottomSheetCallback(new BottomSheetBehavior.BottomSheetCallback() {
+            @Override
+            public void onStateChanged(@NonNull View bottomSheet, int newState) {
+                if(newState == 3){
```
Comment (zachariyaJaveri) [inline app/src/main/java/minicap/concordia/campusnav/screens/MapsActivity.java]: Is there a constant that we can put here? Usually the bottom sheet or bottomSheetBehaviour classes have constants in their class that help bring more meaning

**Review by zachariyaJaveri — COMMENTED** [review]
One small change needed, everything else looks great!

File: app/src/main/java/minicap/concordia/campusnav/screens/MapsActivity.java (hunk 1 above)
Comment (Kayram2710) [reply app/src/main/java/minicap/concordia/campusnav/screens/MapsActivity.java]: Yea i can do it super easy

**Review by zachariyaJaveri — APPROVED** [review]
All good! Everything addressed!
